### ISSUE TITLE
Does not appear ready for PHP 8.0

### ISSUE THREAD

**Issue by patricecampus** [rezaies/moodle-profilefield_conditional#27] opened 2023-04-04 18:40 UTC
**When updating to PHP 8 with Moodle 3.11.13+, we got thoses errors messages :**

line 88 of /user/profile/field/conditional/field.class.php: ArgumentCountError thrown
line 88 of /user/profile/field/conditional/field.class.php: call to array_merge()
line 159 of /user/profile/lib.php: call to profile_field_conditional->edit_field_add()
line 657 of /user/profile/lib.php: call to profile_field_base->edit_field()
line 153 of /user/editadvanced_form.php: call to profile_definition()
line 214 of /lib/formslib.php: call to user_editadvanced_form->definition()
line 155 of /user/editadvanced.php: call to moodleform->__construct()

It would be very helpfull if you could update that great plugin!

**Comment by rezaies** [comment] 2023-05-05 21:02
Closing as duplicate of #25 which is already fixed now.

**Closed as not planned by rezaies** 2023-05-05 21:02 UTC

**Comment by patricecampus** [comment] 2023-05-08 20:23
Thank you
