### ISSUE TITLE
Issue with bulk user upload

### ISSUE THREAD

**Issue by jasimp** [rezaies/moodle-profilefield_conditional#15] opened 2021-07-21 23:46 UTC
Hi 
I am facing an issue while bulk user upload
All the fields are correct. But its showing an error while uploading in the status column like below even the required field already there with correct data

"Please fill the Job Category field. It cannot be left empty based on the value you selected here. (profile_field_User_Category)"

if we remove the field data for "(profile_field_User_Category)" from upload file , as the scenario here, everything going well! and (profile_field_Job_Category) also adding to the user account which said empty in the error.

How to solve this issue.

**Comment by nlatoni** [comment] 2021-10-13 04:16
I ran into this error as well. My workaround is in two places.
line 474 of /admin/tool/uploaduser/locallib.php:
` 
$err = $formfield->edit_validate_field($testuser, 'userupload');
`

starting at line 147 of /user/profile/field/conditional/field.class.php
 
```
public function edit_validate_field($usernew, $method='none') {
        global $DB;

        if ($method === 'userupload') {
            return;
        }
        $errors = array();

```
This will have the user upload process bypass additional conditional validation. The validation really **_should_** be there, but I don't know how to keep it while also processing the CSV.

**Comment by jasimp** [comment] 2021-10-13 05:09
> I ran into this error as well. My workaround is in two places. line 474 of /admin/tool/uploaduser/locallib.php: ` $err = $formfield->edit_validate_field($testuser, 'userupload');`
> 
> starting at line 147 of /user/profile/field/conditional/field.class.php
> 
> ```
> public function edit_validate_field($usernew, $method='none') {
>         global $DB;
> 
>         if ($method === 'userupload') {
>             return;
>         }
>         $errors = array();
> ```
> 
> This will have the user upload process bypass additional conditional validation. The validation really **_should_** be there, but I don't know how to keep it while also processing the CSV.

Thank you nlatoni for your reply
I thought it was the issue with this plugin
Since it is core , is there any option to do with out amending core file

**Comment by rezaies** [comment] 2023-05-05 20:58
Closing as duplicate of #14

**Closed as not planned by rezaies** 2023-05-05 20:58 UTC
